= The Ion Data Interchange Format
Les Hazlewood <les@hazlewood.com>
:revnumber: draft-ionwg-ion-01
:revdate: {docdatetime}
:source-highlighter: pygments
:toc: right
// URIs:
:uri-json: http://tools.ietf.org/html/rfc7159
:uri-rest: http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm
:uri-rfc2119: https://tools.ietf.org/html/rfc2119
:uri-rfc5988: http://tools.ietf.org/html/rfc5988
:uri-rfc5988-links: https://tools.ietf.org/html/rfc5988#section-3
:uri-rfc5988-linkRelType: https://tools.ietf.org/html/rfc5988#section-4
:uri-mediaType-namingReqs: https://tools.ietf.org/html/rfc6838#section-4.2
:uri-rfc-json-value: https://tools.ietf.org/html/rfc7159#section-3
:uri-linkRelType-item: http://tools.ietf.org/html/rfc6573#section-2.1
:uri-ecmaScript-5-1: http://www.ecma-international.org/ecma-262/5.1
:uri-ecmaScript-5-1-15-12: http://www.ecma-international.org/ecma-262/5.1/#sec-15.12
:uri-IRIs: http://tools.ietf.org/html/rfc3987
:uri-IRIs-3-1: http://tools.ietf.org/html/rfc3987#section-3.1
:uri-URIs: http://tools.ietf.org/html/rfc3986
:uri-links: http://tools.ietf.org/html/rfc5988#section-3
:uri-IANA-consideration-guidelines: https://tools.ietf.org/html/rfc5226
:uri-semver: http://semver.org

A human-friendly JSON-based hypermedia type for machine data interchange.

.Abstract

This document specifies the Ion Data Interchange Format, a simple and human-friendly
{uri-json}[JSON]-based hypermedia type for machine data interchange.

.Status

This Internet-Draft is a working document of the Ion Working Group (IWG).  Note
that other groups may also distribute working documents as Internet-Drafts.

Internet-Drafts are draft documents valid for a maximum of six months
and may be updated, replaced, or obsoleted by other documents at any
time.  It is inappropriate to use Internet-Drafts as reference
material or to cite them other than as "work in progress."

This Internet-Draft will expire on 31 July 2016.

.Copyright Notice

Copyright (c) Les Hazlewood 2013-2015 and persons identified as document authors.
All rights reserved.

:sectnums:

== Introduction

HTTP is commonly used to transfer data in many different data formats. With
the advent of the {uri-rest}[REST] architectural style, HTTP-enabled
applications often support {uri-json}[JSON] as data format for data exchange.
However, JSON's simple grammar can support virtually any data model - additional
context is required for machine clients and servers to interpret data and
metadata in important ways.

Ion codifies specific name/value pairs within JSON objects to better
facilitate JSON-based data and metadata exchange between machines.  And while machine interchange is the primary goal, Ion's second most important design goal is to enable intuitive and context-relevant structure so Ion content is very easy to understand for humans, even if they do not know what Ion is.

=== Terminology

These terms are defined by this specification:

.Member
A JSON name/value pair as defined in https://tools.ietf.org/html/rfc7159#section-4[RFC 7159].

.Metadata
A set of data that provides information about other data.

.Meta Object
A JSON object with one or more members that all represent Metadata.

.Root Object
The single JSON object at the root of an Ion content structure.

.Ion Object
A JSON object with a Meta Object member named `meta`.

.Resource
An Ion Object that has one or more members in addition to its `meta` member.

.Collection Resource
A Resource that has an array member named `items` in addition to its `meta` member.

.Link
An Ion Object where its `meta` member contains an {uri-IRIs}[IRI] member named `href`.  This is the Ion representation of a {uri-links}[Web Link] that enables linking from one Resource to another.

=== Media Type Name and Version

The Media Type name assigned for Ion content is:

`application/ion+json`

This format may be referred to as "Ion 1.0". This specification uses "Ion" internally.

Any future version will be represented with a media type parameter named `v` with a {uri-semver}[semantic version]
value.  For example (non-normative):

`application/ion+json;v=2`

=== Examples

The following examples are non-normative.

==== Example Resources

A JSON object without metadata is treated like a standard JSON object:

.Example JSON Object Without Metadata
[source,json]
----
{
  "firstName": "Bob",
  "lastName": "Smith",
  "birthDate": "1980-01-23"
}
----

An Ion _Resource_ is a JSON object with a Metadata member named `meta` in addition to one or more other members (name/value pairs):

.Example Ion Resource
[source,json]
----
{
  "meta": { "href": "https://api.example.com/users/1" },
  "firstName": "Bob",
  "lastName": "Smith",
  "birthDate": "1980-01-23"
}
----

==== Example Collection Resources

An Ion Collection Resource is an Ion Resource that has an array member named `items`.

An example empty Ion Collection Resource:

.Example Empty Ion Collection Resource:
[source,json]
----
{
  "meta": { "href": "https://api.example.com/users" },
  "items": []
}
----

Ion Collection Resources can also support pagination, for example:

.Example Paginated Ion Collection Resource:
[source,javascript]
----
{
  "meta": { "href": "https://api.example.com/users" },
  "offset": 0,
  "limit": 25,
  "size": 218,
  "first": { "meta": { "href": "https://api.example.com/users", "rel": ["collection"] } },
  "previous": null,
  "next": { "meta": { "href": "https://api.example.com/users?offset=25", "rel": ["collection"] } },
  "last": { "meta": { "href": "https://api.example.com/users?offset=200", "rel": ["collection"] } },
  "items": [
    {
      "meta": { "href": "https://api.example.com/users/1" },
      "firstName": "Bob",
      "lastName": "Smith",
      "birthDate": "1977-04-18"
    },
    //... items 2-24 omitted for brevity
    {
      "meta": { "href": "https://api.example.com/users/25" },
      "firstName": "Jane",
      "lastName": "Doe",
      "birthDate": "1980-01-23"
    }
  ]
}
----

==== Example Links

An Ion Link is an Ion Object representation of a {uri-rfc5988}[web link] to another
resource. For example, assume that a user "Joe" is an employee of "Acme"
corporation.  A link within the "Joe" resource to Joe's employer might be
represented as follows:

.Ion Link from one resource to another:
[source,json]
----
{
  "name": "Joe",
  "employer": { "meta": { "href": "https://api.example.com/corporations/acme" } }
}
----

=== Notational Conventions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described {uri-rfc2119}[RFC2119] when they appear in UPPERCASE.  If these words are used without being spelled in uppercase then they are
to be interpreted with their normal natural language meanings, without any normative meaning.


[[content-structure]]
== Content Structure

Ion content MUST have exactly one root JSON object, called the _Root Object_.  The Root Object MAY contain
name/value pairs called 'members' and any level of nested JSON objects.

[[metadata]]
== Metadata

An JSON object MAY contain a _Meta Object_ member named `meta`. If present, the _Meta Object_ represents data about its immediate parent JSON object. The _Meta Object_ is OPTIONAL.

An Ion parser MUST identify a member as a _Meta Object_ if and only if:

1. The member name is equal to the case-sensitive octet sequence `meta` and
2. The member value is a JSON Object that has one or more members.

If a member name is equal to the case-sensitive octet sequence `meta` and the member value is NOT a JSON Object (i.e. it is an array, number, string or the octet sequence literals `null`, `false`, or `true` as defined by {uri-rfc-json-value}[RFC 7159, Section 3]), an Ion parser MUST NOT identify the member as a _Meta Object_.

If a member name is equal to the case-sensitive octet sequence `meta` and the member value is an empty JSON Object with no members, an Ion parser MUST NOT identify the member as a _Meta Object_.

If a member name is not equal to the case-sensitive octet sequence `meta`, an Ion parser MUST NOT identify a member as a _Meta Object_.

The member names within an identified _Meta Object_ MUST be unique; Ion parsers MUST either
reject _Meta Object_ members with duplicate member names or use a JSON
parser that returns only the lexically last duplicate member, as specified
in {uri-ecmaScript-5-1-15-12}[Section 15.12 (The JSON Object)] of {uri-ecmaScript-5-1}[ECMAScript 5.1].

A _Meta Object_ MAY contain members that are not defined in the Ion Metadata Member Registry.  Any member not understood by an Ion parser SHOULD be ignored.

[[links]]
== Links

An Ion Link is an Ion Object where its `meta` member contains an {uri-IRIs}[IRI] member named `href`. An Ion Link therefore is a JSON serialization of a {uri-rfc5988}[web link] to another resource.

An Ion parser MUST identify a member as an _Ion Link_ if:

1. The member is a _Meta Object_ as defined in Section 3 and
2. The Meta Object contains an {uri-IRIs}[IRI] member with a name equal to the case-sensitive octet sequence `href`.

If the Meta Object `href` value is `null`, not a string, an empty string, or a whitespace-only (blank) string, an Ion parser MUST NOT identify the member as an _Ion Link_.

It is possible for an Ion Object to be both an _Ion Resource_ and an _Ion Link_ if both respective parsing conditions are satisfied.

A non-normative example of a minimal Ion link:

.Example simplest Ion link:
[source,json]
----
{ "meta": { "href": "https://api.example.com/corporations/acme" } }
----

A non-normative example of an Ion Object that is both an Ion Resource and an Ion Link:

.Example Ion Object that is both an Ion Resource and an Ion Link:
[source,json]
----
{
  "meta": { "href": "https://api.example.com/corporations/acme" },
  "name": "Acme, Inc."
}
----

=== Link Relation Types

All Ion links have one or more <<links, link relation types>>.  A link's total set of link relation types is the set union of the link's implicit link relation type and the link's explicit link relation types.

==== Implicit Link Relation Type

All Ion links have exactly one implicit link relation type.  The implicit link relation type can be one of three possible values depending on where the link is located in the Ion content:

1. Root Object
2. Named Link
3. Collection Resource `items` array element

===== Root Object Implicit Link Relation Type

If the Root Object is also found to be an Ion Link, it has an implicit link relation type of `self`.

A non-normative example of a Root Object that is also an Ion Link:

[source,json]
----
{
  "meta": { "href": "https://api.example.com/users/1" },
  "name": "Joe"
}
----

===== Named Link Implicit Link Relation Type

If a JSON Object member value is an Ion Link, the Ion Link is implicitly assigned a link relation type that equals the member name.

A non-normative example:

[source,json]
----
{
  "employer": { "meta": { "href": "https://api.example.com/corporations/acme" } }
}
----

The above example shows an Ion Link member named `employer`.  The octet sequence `employer` is therefore assigned as the link's implicit link relation type.

===== Collection Item Implicit Link Relation Type

Any Ion Link in a Collection Resource's `items` array is implicitly assigned the {uri-linkRelType-item}[`item`] link relation type.

A non-normative example:

[source,json]
----
{
  "meta": { "href": "https://api.example.com/users" },
  "items": [
    { "meta": { "href": "https://api.example.com/users/1" } },
    { "meta": { "href": "https://api.example.com/users/2" } }
  ]
}
----

The above example has 2 Ion Links in its `items` array.  Each of these 2 links are implicitly assigned the {uri-linkRelType-item}[`item`] link relation type.

==== Explicit Link Relation Types

An Ion link MAY have one or more explicitly defined link relation types declared as an array of strings assigned to the link Meta Object's `rel` member.

A non-normative example of a link with an explicitly defined link relation type:

.Example Ion Link with explicit link relation type:
[source,json]
----
{ "meta": { "href": "https://cdn.example.com/example.ico", "rel": ["icon"] } }
----

The above example has an explicit link relation type of http://www.w3.org/TR/html5/links.html#rel-icon[`icon`].

More than one explicit link relation type MAY be defined in the `rel` array.

Ion parsers MUST NOT recognize any non-string value in the `rel` array as a link relation type.

Ion parsers MUST treat null or empty `rel` values as if the `rel` property was not defined at all.

== Registered Metadata Member Names

The following member names are registered in the IANA Ion Metadata member registry
defined in [TBD].  None of the members defined below are intended to be mandatory
in all cases, but rather, provide an initial set likely to be useful for common
use cases.

=== `href`

The `href` (hypermedia reference) member identifies the target {uri-IRIs}[IRI] (Internationalized Resource Identifier) location of the resource. The `href` value is a case-sensitive {uri-IRIs}[IRI] value.

If an `href` member exists, Ion parsers MUST identify the Meta Object as an Ion Link in addition to any other Ion Object identified by the Meta Object.

Note that in the common case, target IRIs and context IRIs will also be
{uri-URIs}[URI]s (RFC 3986), because many protocols (such as HTTP) do not support
dereferencing IRIs.  In serializations that do not support IRIs, IRIs will be
converted to URIs according to {uri-IRIs-3-1}[RFC 3987 Section 3.1].

Use of this member is OPTIONAL.

=== `mediaType`

The `mediaType` member identifies the resource's https://tools.ietf.org/html/rfc6838[Media Type].  The `mediaType` value is a case-insensitive string as defined by {uri-mediaType-namingReqs}[RFC 6838 Section 4.2]. Use of this member is OPTIONAL.

=== `rel`

The `rel` member identifies one or more explicit http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1[Link Relation Type]s assigned to an Ion Link.  The value is a JSON array of strings.  Each string MUST conform to the `relation-type` grammar definition in https://tools.ietf.org/html/rfc5988#section-5[RFC 5988 Section 5].

Use of this member is OPTIONAL.

A _Link_ to a _Collection Resource_ SHOULD contain a `rel` member that has at least the `collection` relation specified.

== IANA Considerations

=== Ion Metadata Member Registry

This specification establishes the IANA Ion Metadata Member Registry for Ion
Metadata Member Names.  The registry records the Member Name and a reference to
the specification that defines it.  This specification registers the Member Names
defined in Section 5.

Values are registered on a
{uri-IANA-consideration-guidelines}[specification required] (RFC 5226) basis
after a review period on the Ion Working Group (IWG)
https://github.com/ionwg/ion-doc[ion-doc GitHub repository], on the advice of
one or more Designated Experts. However, to allow
for the allocation of values prior to publication, the Designated Expert(s) may
approve registration once they are satisfied that such a specification will be
published.

Registration requests must filed as an
https://github.com/ionwg/ion-doc/issues[ion-doc GitHub issue] for review and
comment, with an appropriate subject (e.g., "Request to register metadata
member: example").

Within the review period, the Designated Expert(s) will either approve or deny
the registration request, communicating this decision by closing the issue.
Denials should include an explanation and, if applicable, suggestions as to
how to make the request successful.  Registration requests that are undetermined
for a period longer than 21 days can be brought to the IWG's attention using
@mentions in a new comment appended to the GitHub issue for resolution.

Criteria that should be applied by the Designated Expert(s) includes determining
whether the proposed registration duplicates existing functionality, determining
whether it is likely to be of general applicability or whether it is useful only
for a single application, and whether the registration description is clear.

IANA must only accept registry updates from the Designated Expert(s) and should
direct all requests for registration to the https://github.com/ionwg/ion-doc/issues[Ion issue tracker].

It is suggested that multiple Designated Experts be appointed who are able to
represent the perspectives of different applications using this specification,
in order to enable broadly-informed review of registration decisions.  In cases
where a registration decision could be perceived as creating a conflict of
interest for a particular Expert, that Expert should defer to the judgment of
the other Expert(s).

Proposed registry description information:

* Protocol Category: Ion
* Registry Location: http://www.iana.org/assignments/ion
* Webpage Title: Ion
* Registry Name: Ion Metadata Members

==== Registration Template

.Member Name:
The name requested (e.g., "href"). This name is case-sensitive.  Names may not
match other registered names in a case-insensitive manner unless the
Designated Expert(s) state that there is a compelling reason to allow an
exception in this particular case.

.Member Description
Brief description of the Member (e.g., "Resource target IRI location").

.Change Controller:
For Standards Track RFCs, state "IESG".  For others, give the name of the
responsible party.  Other details (e.g., postal address, email address, home
page URI) may also be included.

.Specification Document(s):
Reference to the document(s) that specify the parameter, preferably including
URI(s) that can be used to retrieve copies of the document(s).  An indication
of the relevant sections may also be included but is not required.

[appendix]
== Appendix

Acknowledgements

The authors acknowledge that the design of the Ion data format was initially influenced by design concepts in https://tools.ietf.org/html/rfc4287[RFC 4287, The Atom Syndication Format], specifically the parallels between Atom's 'Entry' and 'Container' concepts and Ion's 'Resource' and 'Collection Resource' concepts, respectively.  The name 'Ion' is a playful nod to the Atom name, honoring this heritage.

Ion's `meta` member concept was largely influenced by a discussion on JSON linking between Tim Berners-Lee and Mark Nottingham as described in Mark Nottingham's https://www.mnot.net/blog/2011/11/25/linking_in_json[Linking In JSON blog post].  The Ion `meta` concept codifies this idea and defines a registry for `meta` members useful for hypermedia interchange.

.Authors' Addresses

....
Les Hazlewood
Email: les@hazlewood.com
URI: http://leshazlewood.com
Company: Stormpath
Company URI: https://stormpath.com
....
