= The Ion Hypermedia Type
Les Hazlewood <les@hazlewood.com>
:revnumber: draft-ionwg-ion-01
:revdate: {docdatetime}
:source-highlighter: pygments
:toc: right
// URIs:
:uri-json: http://tools.ietf.org/html/rfc7159
:uri-rest: http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm
:uri-rfc2119: https://tools.ietf.org/html/rfc2119
:uri-rfc5988: http://tools.ietf.org/html/rfc5988
:uri-rfc5988-links: https://tools.ietf.org/html/rfc5988#section-3
:uri-rfc5988-linkRelType: https://tools.ietf.org/html/rfc5988#section-4
:uri-rfc7231-methods: https://tools.ietf.org/html/rfc7231#section-4.1
:uri-mediaType-namingReqs: https://tools.ietf.org/html/rfc6838#section-4.2
:uri-rfc-json-value: https://tools.ietf.org/html/rfc7159#section-3
:uri-linkRelType-item: http://tools.ietf.org/html/rfc6573#section-2.1
:uri-ecmaScript-5-1: http://www.ecma-international.org/ecma-262/5.1
:uri-ecmaScript-5-1-15-12: http://www.ecma-international.org/ecma-262/5.1/#sec-15.12
:uri-IRIs: http://tools.ietf.org/html/rfc3987
:uri-IRIs-3-1: http://tools.ietf.org/html/rfc3987#section-3.1
:uri-URIs: http://tools.ietf.org/html/rfc3986
:uri-links: http://tools.ietf.org/html/rfc5988#section-3
:uri-IANA-consideration-guidelines: https://tools.ietf.org/html/rfc5226
:uri-semver: http://semver.org

A human-friendly JSON-based hypermedia type for machine data interchange.

.Abstract

This document specifies the Ion Hypermedia Type, a simple and human-friendly
{uri-json}[JSON]-based hypermedia type for machine data interchange.

.Status

This Internet-Draft is a working document of the Ion Working Group (IWG).  Note
that other groups may also distribute working documents as Internet-Drafts.

Internet-Drafts are draft documents valid for a maximum of six months
and may be updated, replaced, or obsoleted by other documents at any
time.  It is inappropriate to use Internet-Drafts as reference
material or to cite them other than as "work in progress."

This Internet-Draft will expire on 30 June 2016.

.Copyright Notice

Copyright (c) Les Hazlewood 2013-2016 and persons identified as document authors.  All rights reserved.

:sectnums:

== Introduction

HTTP is commonly used to transfer data in many different data formats. With the advent of the {uri-rest}[REST]
architectural style and the success of the JavaScript programming language, HTTP-enabled applications regularly
support {uri-json}[JSON] as a preferred data format for data exchange.

However, this poses a challenge for machine data exchange at web scale across heterogeneous domains and organizations;
JSON's simple grammar can support virtually any data model - additional context is required for machine clients and
servers to automate information discovery and exchange via hypermedia controls.

Ion codifies specific name/value pairs within JSON objects to help automate JSON-based hypermedia interchange between
machines.  And while machine data and metadata interchange is the primary goal, Ion's second most important design
goal is to enable intuitive and context-relevant structure so Ion content is very easy to understand for humans, even
if they do not know what Ion is.

=== Terminology

These terms are defined by this specification:

.Member
A JSON name/value pair as defined in https://tools.ietf.org/html/rfc7159#section-4[RFC 7159].

.Metadata
A set of data that provides information about other data.

.Meta Object
A JSON object with one or more members that all represent Metadata.

.Root Object
The single JSON object at the root of an Ion content structure.

.Ion Object
A JSON object with a Meta Object member named `meta`.

.Ion Collection
An Ion Object with an additional array member named `items`.

.Resource
An Ion Object that has one or more members in addition to its `meta` member.

.Collection Resource
An Ion Collection that has one or more members in addition to its `meta` and `items` members.

.Link
An Ion Object where its `meta` member contains an {uri-IRIs}[IRI] member named `href`.  This is the Ion representation of a {uri-links}[Web Link] that enables linking from one resource to another.

.Form
An Ion Collection of form fields that represent data that may be submitted to a linked resource location.

=== Media Type Name and Version

The Media Type name assigned for Ion content is:

`application/ion+json`

This format may be referred to as "Ion 1.0". This specification uses "Ion" internally.

Any future version will be represented with a media type parameter named `v` with a {uri-semver}[semantic version]
value.  For example (non-normative):

`application/ion+json;v=2`

=== Examples

All following examples are non-normative.

==== Example Objects

A JSON object without metadata is treated as a standard JSON object:

.Example JSON Object Without Metadata
[source,json]
----
{
  "firstName": "Bob",
  "lastName": "Smith",
  "birthDate": "1980-01-23"
}
----

An Ion _Resource_ is a JSON object with a Metadata member named `meta` in addition to one or more other members (name/value pairs):

.Example Ion Resource
[source,json]
----
{
  "meta": { "href": "https://example.io/users/1" },
  "firstName": "Bob",
  "lastName": "Smith",
  "birthDate": "1980-01-23"
}
----

==== Example Collections

An Ion Collection is an Ion Object that has an array member named `items` in addition to its `meta` member.  This `meta`
member can reflect metadata about the items array or elements within the array, something the JSON grammar cannot do
directly.

An example empty Ion Collection:

.Example Empty Ion Collection:
[source,json]
----
{
  "meta": { "href": "https://example.io/users" },
  "items": []
}
----

Ion Collections can also support pagination, for example:

.Example Paginated Ion Collection:
[source,javascript]
----
{
  "meta": { "href": "https://example.io/users", "rel": ["collection"] },
  "offset": 0,
  "limit": 25,
  "size": 218,
  "first": { "meta": { "href": "https://example.io/users", "rel": ["collection"] } },
  "previous": null,
  "next": { "meta": { "href": "https://example.io/users?offset=25", "rel": ["collection"] } },
  "last": { "meta": { "href": "https://example.io/users?offset=200", "rel": ["collection"] } },
  "items": [
    {
      "meta": { "href": "https://example.io/users/1" },
      "firstName": "Bob",
      "lastName": "Smith",
      "birthDate": "1977-04-18"
    },
    //... items 2-24 omitted for brevity
    {
      "meta": { "href": "https://example.io/users/25" },
      "firstName": "Jane",
      "lastName": "Doe",
      "birthDate": "1980-01-23"
    }
  ]
}
----

==== Example Links

An Ion Link is an Ion Object representation of a {uri-rfc5988}[web link] to another
resource. For example, assume that someone named "Joe" is an employee of "Acme"
corporation.  A link within the "Joe" resource to Joe's employer might be
represented as follows:

.Ion Link from one resource to another:
[source,json]
----
{
  "name": "Joe",
  "employer": { "meta": { "href": "https://example.io/corporations/acme" } }
}
----

==== Example Form

An Ion Form ensures that resource transitions that support data submissions can be discovered automatically
(colloquially referred to as https://en.wikipedia.org/wiki/HATEOAS[HATEOS]).

.Example Ion Form
[source,json]
----
{
  "meta": { "href": "https://example.io/loginAttempts", "rel":["create-form"], "method": "POST"},
  "items": [
    { "name": "username" },
    { "name": "password", "type": "password" },
    { "name": "favoriteColor", "label": "Favorite Color", "options": {
        "items": [
          { "label": "Red", "value": "red", "selected": true, "enabled": false },
          { "label": "Blue", "value": "blue" }
        ]
      }
    },
    { "name": "visitedContinents", "type": "string", "multiple": true, "options": {
        "items": [
          { "label": "Africa", "value": "af" },
          { "label": "North America", "value": "na", "selected": true },
          { "label": "South America", "value": "sa" },
          { "label": "Europe", "value": "eu", "selected": true },
          { "label": "Asia", "value": "as", "selected": true }
          { "label": "Oceania", "value": "oc" }
          { "label": "Antarctica", "value": "an" }
        ]
      }
    },
    { "name": "favoriteContinent", "type": "string", "options": {
        "items": [
          { "label": "Africa", "value": "af" },
          { "label": "North America", "value": "na" },
          { "label": "South America", "value": "sa" },
          { "label": "Europe", "value": "eu" },
          { "label": "Asia", "value": "as" }
          { "label": "Oceania", "value": "oc" }
          { "label": "Antarctica", "value": "an", "selected": true }
        ]
      }
    }
  ]
}
----

=== Notational Conventions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described {uri-rfc2119}[RFC2119] when they appear in UPPERCASE.  If these words are used without being spelled in uppercase then they are
to be interpreted with their normal natural language meanings, without any normative meaning.


[[content-structure]]
== Content Structure

Ion content MUST use UTF-8 encoding.  Other encodings MUST NOT be used.

Ion content MUST have exactly one root JSON object, called the _Root Object_.  The Root Object MAY contain
name/value pairs called 'members' and any level of nested JSON objects.

[[metadata]]
== Metadata

A JSON object MAY contain a _Meta Object_ member named `meta`. If present, the _Meta Object_ represents data about its immediate parent JSON object. The _Meta Object_ is OPTIONAL.

An Ion parser MUST identify a member as a _Meta Object_ if and only if:

1. The member name is equal to the case-sensitive octet sequence `meta` and
2. The member value is a JSON Object that has one or more members.

If a member name is equal to the case-sensitive octet sequence `meta` and the member value is NOT a JSON Object (i.e. it is an array, number, string or the octet sequence literals `null`, `false`, or `true` as defined by {uri-rfc-json-value}[RFC 7159, Section 3]), an Ion parser MUST NOT identify the member as a _Meta Object_.

If a member name is equal to the case-sensitive octet sequence `meta` and the member value is an empty JSON Object with no members, an Ion parser MUST NOT identify the member as a _Meta Object_.

If a member name is not equal to the case-sensitive octet sequence `meta`, an Ion parser MUST NOT identify a member as a _Meta Object_.

The member names within an identified _Meta Object_ MUST be unique; Ion parsers MUST either
reject _Meta Object_ members with duplicate member names or use a JSON
parser that returns only the lexically last duplicate member, as specified
in {uri-ecmaScript-5-1-15-12}[Section 15.12 (The JSON Object)] of {uri-ecmaScript-5-1}[ECMAScript 5.1].

A _Meta Object_ MAY contain members that are not defined in the Ion Metadata Member Registry.  Any member not understood by an Ion parser SHOULD be ignored.

[[links]]
== Links

An Ion Link is an Ion Object where its `meta` member contains an {uri-IRIs}[IRI] member named `href`. An Ion Link therefore is a JSON serialization of a {uri-rfc5988}[web link] to another resource.

An Ion parser MUST identify a member as an _Ion Link_ if:

1. The member is a _Meta Object_ as defined in Section 3 and
2. The Meta Object contains an {uri-IRIs}[IRI] member with a name equal to the case-sensitive octet sequence `href`.

If the Meta Object `href` value is `null`, not a string, an empty string, or a whitespace-only (blank) string, an Ion parser MUST NOT identify the member as an _Ion Link_.

It is possible for an Ion Object to be both an _Ion Resource_ and an _Ion Link_ if both respective parsing conditions are satisfied.

A non-normative example of a minimal Ion link:

.Example simplest Ion link:
[source,json]
----
{ "meta": { "href": "https://example.io/corporations/acme" } }
----

A non-normative example of an Ion Object that is both an Ion Resource and an Ion Link:

.Example Ion Object that is both an Ion Resource and an Ion Link:
[source,json]
----
{
  "meta": { "href": "https://example.io/corporations/acme" },
  "name": "Acme, Inc."
}
----

=== Link Relation Types

All Ion links have one or more <<links, link relation types>>.  A link's total set of link relation types is the set union of the link's implicit link relation type and the link's explicit link relation types.

==== Implicit Link Relation Type

All Ion links have exactly one implicit link relation type.  The implicit link relation type can be one of three possible values depending on where the link is located in the Ion content:

1. Root Object
2. Named Link
3. Ion Collection `items` array element

===== Root Object Implicit Link Relation Type

If the Root Object is also found to be an Ion Link, it has an implicit link relation type of `self`.

A non-normative example of a Root Object that is also an Ion Link:

[source,json]
----
{
  "meta": { "href": "https://example.io/users/1" },
  "name": "Joe"
}
----

===== Named Link Implicit Link Relation Type

If a JSON Object member value is an Ion Link, the Ion Link is implicitly assigned a link relation type that equals the member name.

A non-normative example:

[source,json]
----
{
  "employer": { "meta": { "href": "https://example.io/corporations/acme" } }
}
----

The above example shows an Ion Link member named `employer`.  The octet sequence `employer` is therefore assigned as the link's implicit link relation type.

===== Collection Item Implicit Link Relation Type

Any Ion Link in an Ion Collection's `items` array is implicitly assigned the {uri-linkRelType-item}[`item`] link relation type.

A non-normative example:

[source,json]
----
{
  "meta": { "href": "https://example.io/users" },
  "items": [
    { "meta": { "href": "https://example.io/users/1" } },
    { "meta": { "href": "https://example.io/users/2" } }
  ]
}
----

The above example has 2 Ion Links in its `items` array.  Each of these 2 links are implicitly assigned the {uri-linkRelType-item}[`item`] link relation type.

==== Explicit Link Relation Types

An Ion link MAY have one or more explicitly defined link relation types declared as an array of strings assigned to the link Meta Object's `rel` member.

A non-normative example of a link with an explicitly defined link relation type:

.Example Ion Link with explicit link relation type:
[source,json]
----
{ "meta": { "href": "https://cdn.example.com/example.ico", "rel": ["icon"] } }
----

The above example has an explicit link relation type of http://www.w3.org/TR/html5/links.html#rel-icon[`icon`].

More than one explicit link relation type MAY be defined in the `rel` array.

Ion parsers MUST NOT recognize any non-string value in the `rel` array as a link relation type.

Ion parsers MUST treat null or empty `rel` values as if the `rel` property was not defined at all.

[[forms]]
== Forms

If data can be submitted to a linked resource location, information about that data must be made available to a
hypermedia client so it can collect and then submit the data.

An Ion Form represents named data values that may be submitted to a linked resource location. Each named data value,
along with any additional information (such as constraints) for that data, is collectively called a form _field_.  An
Ion Form is then effectively a collection of _fields_ with additional metadata that controls how the form
fields are submitted to a linked resource location.

Because a form always reflects a linked resource location, every Ion Form can also be considered an Ion Link because
it has a `meta` `href` member.

Additionally, because every Ion Form has metadata and array of fields, every Ion Form is therefore also an
Ion Collection (a collection of fields).

[[form-structure]]
=== Form Structure

An Ion Form is both an Ion Link and an Ion Collection and has the following additional requirements:

1. An Ion Form's `meta` object MUST have a `rel` member that contains one of the octet sequences `form`, `edit-form`, `create-form` or `query-form`.
2. An Ion Form's `items` array MUST contain one or more Ion Form Fields.
3. An Ion Form's `items` array MUST NOT contain elements that are not Ion Form Fields.
4. An Ion Form's `items` array MUST NOT be `null` or empty.

A non-normative example:

[source,json]
----
{
  "meta": { "href": "https://example.io/loginAttempts", "rel":["form"], "method": "POST"},
  "items": [
    { "name": "username" },
    { "name": "password", "type": "password" }
  ]
}
----

[[form-fields]]
=== Form Fields

An Ion Form Field is a JSON object in an Ion Form's `items` array.

An Ion Form Field MUST have a string member named `name`.

Each Ion Form Field within an Ion Form's `items` array MUST have a unique `name` value compared to any other Form Field
within the same array.

[[form-field-members]]
=== Form Field Members

An Ion Form Field has one or more of the following members.

==== `enabled`

The `enabled` member indicates whether or not the field `value` may be modified or submitted to the form's linked resource location.

The `enabled` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `false` value indicates that the field value MUST NOT be modified or submitted to the form's linked resource location.

If the `enabled` member is not present, or if it present and equal to `true`, the field may be modified or submitted to the form's linked resource location.

If a field should be considered enabled, it is RECOMMENDED to omit the `enabled` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

==== `gt`

The `gt` member indicates that the field `value` must be greater than the specified `gt` member value.

The `gt` member is a date or a number. The `gt` value MUST conform to the data type specified by the field `type`.
This member MUST NOT be used with a non-date or non-number field `type`.

If the `gt` member is present, the field `value` must be greater than the `gt` value.

If the `gt` member is not present, there is no 'greater than' restriction on the field `value`.

The `gt` and `gte` members are mutually exclusive - if one is declared, the other MUST NOT be declared.

Use of this member is OPTIONAL.

==== `gte`

The `gte` member indicates that the field `value` must be greater than or equal to the specified `gte` member value.

The `gte` member is a date or a number. The `gte` value MUST conform to the data type specified by the field `type`.
This member MUST NOT be used with a non-date or non-number field `type`.

If the `gte` member is present, the field `value` must be greater than or equal to the `gte` value.

If the `gte` member is not present, there is no 'greater than or equal to' restriction on the field `value`.

The `gt` and `gte` members are mutually exclusive - if one is declared, the other MUST NOT be declared.

Use of this member is OPTIONAL.

==== `label`

The `label` member is a string description of the field that may be used to enhance usability.

Use of this member is OPTIONAL.

==== `lt`

The `lt` member indicates that the field `value` must be less than the specified `lt` member value.

The `lt` member is a date or a number. The `lt` value MUST conform to the data type specified by the field `type`.
This member MUST NOT be used with a non-date or non-number field `type`.

If the `lt` member is present, the field `value` must be less than the `lt` value.

If the `lt` member is not present, there is no 'less than' restriction on the field `value`.

The `lt` and `lte` members are mutually exclusive - if one is declared, the other MUST NOT be declared.

Use of this member is OPTIONAL.

==== `lte`

The `lte` member indicates that the field `value` must be less than or equal to the specified `lte` member value.

The `lte` member is a date or a number. The `lte` value MUST conform to the data type specified by the field `type`.
This member MUST NOT be used with a non-date or non-number field `type`.

If the `lte` member is present, the field `value` must be less than or equal to the `lte` value.

If the `lte` member is not present, there is no 'less than or equal to' restriction on the field `value`.

The `lt` and `lte` members are mutually exclusive - if one is declared, the other MUST NOT be declared.

Use of this member is OPTIONAL.

==== `maxlength`

The `maxlength` member is an integer that specifies the maximum number of characters the field `value` may contain.

==== `minlength`

The `minlength` member is an integer that specifies the minimum number of characters the field `value` must contain.

==== `mutable`

The `mutable` member indicates whether or not the field value may be modified before it is submitted to the form's linked resource location.

The `mutable` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `false` value indicates that the field value MUST NOT be modified before it is submitted to the form's linked resource location.

If the `mutable` member is not present, or if it present and equal to `true`, the field value may be modified before it is submitted to the form's linked resource location.

If a field should be considered mutable, it is RECOMMENDED to omit the `mutable` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

==== `name`

The `name` member is a string name assigned to the field.

The `name` value MUST NOT be `null`.

The `name` value MUST NOT contain only whitespace.

The `name` value MUST be unique compared to any other Form Field `name` value in the containing Form's `items` array.

Use of this member is REQUIRED.

==== `pattern`

The `pattern` member is a string that defines a regular expression that the field `value` must be validated against.

The `pattern` member MUST NOT be specified on fields with non-string or non-date value types.

Use of this member is OPTIONAL.

==== `placeholder`

The `placeholder` member is a short hint string that describes the expected field `value`.

Use of this member is OPTIONAL.

==== `required`

The `required` member indicates whether or not the field value may equal `null` before is submitted to the form's linked resource location.

The `required` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `true` value indicates that the field value MUST NOT equal `null` before it is submitted to the form's linked resource location.

If the `required` member is not present, or if it present and equal to `false`, the field value MAY equal `null` before it is submitted to the form's linked resource location.

If a field should not be considered required (i.e. optional), it is RECOMMENDED to omit the `required` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

==== `type`

The `type` member specifies the mandatory data type that the `value` member must adhere to.

The `type` member value is a string equal to one of the octet sequences defined in Form Field type Values[form-field-type-values].

If a field does not specify a `type` member, an Ion parser MUST assign a the default `type` of `string` to the field.

If a field also contains an `options` member, and that member has a `multiple` member equal to `true`, then the field type MUST be represented as JSON array of elements of the specified type.

Use of this member is OPTIONAL.

==== `value`

The `value` member reflects the value assigned to the field.

The `value` value MUST conform to the data type specified by the field `type`

Use of this member is OPTIONAL.

==== `visible`

The `visible` member indicates whether or not the field should be made visible by a user agent.  Fields that are not visible are usually used to retain a default value that must be submitted to the form's linked resource location.

The `visible` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `false` value indicates that the field MUST NOT be made visible by a user agent.

If the `visible` member is not present, or if it present and equal to `true`, the field MUST be made visible by a user agent.

If a field should be considered visible, it is RECOMMENDED to omit the `visible` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

[[form-field-type-values]]
=== Form Field `type` Values

A Form Field `type` member value MUST equal one of the following string literal values.

==== `array`

The field `value` must be a JSON array.

If a Form Field has a `type` equal to `array`, that form field MAY also declare an `itemtype` member that identifies
the type of each value in the array.

If an `array` field also contains `gt`, `gte`, `lt`, `lte`, `minlength`, `maxlength` or `pattern` members, those
members' validation rules apply to each item in the array, not the array itself.

If an `array` field also declares an `options` member, the array MUST NOT contain any value that does not appear in a nested `option` `value` member.

==== `binary`

The field `value` must be a JSON string that is a `base64`-encoded octet sequence according to https://tools.ietf.org/html/rfc4648[RFC 4648].  The string MUST NOT contain characters that are not in the `base64` alphabet.

==== `boolean`

The field `value` must be a JSON boolean.

==== `date`

The field `value` must be a JSON string that conforms to the `full-date` grammar defined in https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

==== `datetime`

The field `value` must be a JSON string that conforms to the following https://tools.ietf.org/html/rfc5234[ABNF] grammar:

    time-separator = "T" / "t"
    datetime       = full-date time-separator partial-time

where `full-date` and `partial-time` are defined in https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

==== `datetimetz`

The field `value` must be a JSON string that conforms to the `date-time` grammar defined in https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

==== `decimal`

The field `value` must be a JSON number that contains a decimal point.

==== `duration`

The field `value` must be a JSON string that conforms to the `duration` grammar defined in https://tools.ietf.org/html/rfc3339#appendix-A[RFC 3339 Appendix A].

==== `email`

The field `value` must be a JSON string that is also a valid email address.

==== `integer`

The field `value` must be a JSON number that does not contain a decimal point.

==== `number`

The field `value` must be a JSON number.

==== `password`

The field `value` must be a JSON string and user agents MUST mask the characters so they are not visible to a user.

==== `select`

TBD: select, radio, checkbox

==== `string`

The field `value` must be a JSON string.

==== `time`

The field `value` must be a JSON string that conforms to the `partial-time` grammar defined in https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

==== `timetz`

The field `value` must be a JSON string that conforms to the `full-time` grammar defined in https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

== Registered Metadata Member Names

The following member names are registered in the IANA Ion Metadata member registry
defined in [TBD].  None of the members defined below are intended to be mandatory
in all cases, but rather, provide an initial set likely to be useful for common
use cases.

=== `href`

The `href` (hypermedia reference) member identifies the target {uri-IRIs}[IRI] (Internationalized Resource Identifier) location of the resource. The `href` value is a case-sensitive {uri-IRIs}[IRI] value.

If an `href` member exists, Ion parsers MUST identify the Meta Object as an Ion Link in addition to any other Ion Object identified by the Meta Object.

Note that in the common case, target IRIs and context IRIs will also be
{uri-URIs}[URI]s (RFC 3986), because many protocols (such as HTTP) do not support
dereferencing IRIs.  In serializations that do not support IRIs, IRIs will be
converted to URIs according to {uri-IRIs-3-1}[RFC 3987 Section 3.1].

Use of this member is OPTIONAL.

=== `method`

The `method` member identifies the {uri-rfc7231-methods}[HTTP method] to be used when sending an HTTP request to the associated `href` resource location.  The `method` value is a case-sensitive string as defined by {uri-rfc7231-methods}[RFC 7231 Section 4.1] and safety and idempotent semantics are equivalent to those specified in RFC 7231.

If an `href` member is defined and a peer `method` member is not defined, or the `method` member value is null or not recognized, HTTP `GET` MUST be used if an HTTP request is made to the linked resource.

Use of this member is OPTIONAL.

=== `accepts`

The `accepts` member identifies one or more supported representation https://tools.ietf.org/html/rfc6838[Media Type] that may be submitted to the associated `href` resource location. The value is a JSON array of strings.  Each string in the array MUST be a case-insensitive string as defined by {uri-mediaType-namingReqs}[RFC 6838 Section 4.2].

An HTTP user agent may submit an associated representation that conforms to any of these media types.  If submitting a representation, that representation's media type MUST be specified in the HTTP request https://tools.ietf.org/html/rfc7231#section-3.1.1.5[`Content-Type` header] value as defined by https://tools.ietf.org/html/rfc7231#section-3.4[RFC 7321 Section 3.4. Content Negotiation].

Use of this member is OPTIONAL.

=== `produces`

The `produces` member identifies one or more HTTP response representation https://tools.ietf.org/html/rfc6838[Media Type]s that may be returned from the associated `href` resource location.  The value is a JSON array of strings.  Each string in the array MUST be a case-insensitive string as defined by {uri-mediaType-namingReqs}[RFC 6838 Section 4.2].

An HTTP server may return a response body that conforms to any of these media types; the exact media type will be specified in the HTTP response https://tools.ietf.org/html/rfc7231#section-3.1.1.5[`Content-Type` header] as defined by https://tools.ietf.org/html/rfc7231#section-3.4[RFC 7321 Section 3.4. Content Negotiation].

Use of this member is OPTIONAL.

=== `rel`

The `rel` member identifies one or more explicit http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1[Link Relation Type]s assigned to an Ion Link.  The value is a JSON array of strings.  Each string MUST conform to the `relation-type` grammar definition in https://tools.ietf.org/html/rfc5988#section-5[RFC 5988 Section 5].

Use of this member is OPTIONAL.

A _Link_ to a _Ion Collection_ SHOULD contain a `rel` member that has at least the `collection` relation specified.

== IANA Considerations

=== Ion Metadata Member Registry

This specification establishes the IANA Ion Metadata Member Registry for Ion
Metadata Member Names.  The registry records the Member Name and a reference to
the specification that defines it.  This specification registers the Member Names
defined in Section 5.

Values are registered on a
{uri-IANA-consideration-guidelines}[specification required] (RFC 5226) basis
after a review period on the Ion Working Group (IWG)
https://github.com/ionwg/ion-doc[ion-doc GitHub repository], on the advice of
one or more Designated Experts. However, to allow
for the allocation of values prior to publication, the Designated Expert(s) may
approve registration once they are satisfied that such a specification will be
published.

Registration requests must filed as an
https://github.com/ionwg/ion-doc/issues[ion-doc GitHub issue] for review and
comment, with an appropriate subject (e.g., "Request to register metadata
member: example").

Within the review period, the Designated Expert(s) will either approve or deny
the registration request, communicating this decision by closing the issue.
Denials should include an explanation and, if applicable, suggestions as to
how to make the request successful.  Registration requests that are undetermined
for a period longer than 21 days can be brought to the IWG's attention using
@mentions in a new comment appended to the GitHub issue for resolution.

Criteria that should be applied by the Designated Expert(s) includes determining
whether the proposed registration duplicates existing functionality, determining
whether it is likely to be of general applicability or whether it is useful only
for a single application, and whether the registration description is clear.

IANA must only accept registry updates from the Designated Expert(s) and should
direct all requests for registration to the https://github.com/ionwg/ion-doc/issues[Ion issue tracker].

It is suggested that multiple Designated Experts be appointed who are able to
represent the perspectives of different applications using this specification,
in order to enable broadly-informed review of registration decisions.  In cases
where a registration decision could be perceived as creating a conflict of
interest for a particular Expert, that Expert should defer to the judgment of
the other Expert(s).

Proposed registry description information:

* Protocol Category: Ion
* Registry Location: http://www.iana.org/assignments/ion
* Webpage Title: Ion
* Registry Name: Ion Metadata Members

==== Registration Template

.Member Name:
The name requested (e.g., "href"). This name is case-sensitive.  Names may not
match other registered names in a case-insensitive manner unless the
Designated Expert(s) state that there is a compelling reason to allow an
exception in this particular case.

.Member Description
Brief description of the Member (e.g., "Resource target IRI location").

.Change Controller:
For Standards Track RFCs, state "IESG".  For others, give the name of the
responsible party.  Other details (e.g., postal address, email address, home
page URI) may also be included.

.Specification Document(s):
Reference to the document(s) that specify the parameter, preferably including
URI(s) that can be used to retrieve copies of the document(s).  An indication
of the relevant sections may also be included but is not required.

[appendix]
== Appendix

Acknowledgements

The authors acknowledge that the design of the Ion data format was initially influenced by design concepts in https://tools.ietf.org/html/rfc4287[RFC 4287, The Atom Syndication Format], specifically the parallels between Atom's 'Entry' and 'Container' concepts and Ion's 'Resource' and 'Collection Resource' concepts, respectively.  The name 'Ion' is a playful nod to the Atom name, honoring this heritage.

Ion's `meta` member concept was largely influenced by a discussion on JSON linking between Tim Berners-Lee and Mark Nottingham as described in Mark Nottingham's https://www.mnot.net/blog/2011/11/25/linking_in_json[Linking In JSON blog post].  The Ion `meta` concept codifies this idea and defines a registry for `meta` members useful for hypermedia interchange.

.Authors' Addresses

....
Les Hazlewood
Email: les@hazlewood.com
URI: http://leshazlewood.com
Company: Stormpath
Company URI: https://stormpath.com
....
