= The Ion Data Interchange Format
Les Hazlewood <les@hazlewood.com[@lhazlewood]>
2014-12-27
:revnumber: draft-ionwg-ion-01
:source-highlighter: pygments
:toc: right
// URIs:
:uri-json: http://tools.ietf.org/html/rfc7159
:uri-rest: http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm
:uri-rfc2119: https://tools.ietf.org/html/rfc2119
:uri-rfc5988: http://tools.ietf.org/html/rfc5988
:uri-ecmaScript-5-1: http://www.ecma-international.org/ecma-262/5.1
:uri-ecmaScript-5-1-15-12: http://www.ecma-international.org/ecma-262/5.1/#sec-15.12
:uri-IRIs: http://tools.ietf.org/html/rfc3987
:uri-IRIs-3-1: http://tools.ietf.org/html/rfc3987#section-3.1
:uri-URIs: http://tools.ietf.org/html/rfc3986
:uri-links: http://tools.ietf.org/html/rfc5988#section-3
:uri-IANA-consideration-guidelines: https://tools.ietf.org/html/rfc5226

draft-ionwg-ion-01

.Abstract

This document specifies the Ion Data Interchange Format, a simple
{uri-json}[JSON]-based content and metadata hypermedia type suitable for data
interchange.

.Status

This Internet-Draft is a working document of the Ion Working Group (IWG).  Note
that other groups may also distribute working documents as Internet-Drafts.

Internet-Drafts are draft documents valid for a maximum of six months
and may be updated, replaced, or obsoleted by other documents at any
time.  It is inappropriate to use Internet-Drafts as reference
material or to cite them other than as "work in progress."

This Internet-Draft will expire on 30 June 2015.

.Copyright Notice

Copyright (c) Les Hazlewood 2013-2015 and persons identified as document authors.
All rights reserved.

== Introduction

HTTP is commonly used to transfer data in many different data formats. With
the advent of the {uri-rest}[REST] architectural style, HTTP-enabled
applications often support {uri-json}[JSON] as data format for data exchange.
However, JSON's simple grammar can support virtually any data model - additional
context is required for machine clients and servers to interpret data and
metadata in important ways.

Ion exists to codify specific name/value pairs within a JSON object to better
facilitate JSON-based data and metadata exchange between machine clients and
servers. As such, Ion does not define a new data grammar - it is a
Media Subtype of `application/json`.

=== Terminology

These terms are defined by this specification:

.Metadata
Data about a resource.

.Meta Object
A JSON object that contains resource metadata.

.Instance Resource
A JSON object that represents a single data resource and its metadata.

.Collection Resource
A JSON object that represents a collection of other resources and the
collection's metadata.

.Link
A JSON serialization of a {uri-links}[Web Link] that enables linking from
one resource to another.

=== Media Type Name and Version

The Media Type name assigned for Ion documents is:

`application/ion+json`

For convenience, these formats may be referred to collectively as "Ion 1.0".
This specification uses "Ion" internally.

=== Examples

The following examples are non-normative.

==== Example Instance Resources

A single Ion instance resource without metadata is simply a standard JSON object:

.Example Ion Instance Resource Without Metadata
[source,json]
----
{
  "firstName": "Bob",
  "lastName": "Smith",
  "birthDate": "1980-01-23"
}
----

A single Ion instance resource with metadata is a JSON object that has a direct
child `meta` name/value pair in addition to its other member name/value pairs:

.Example Ion Instance Resource With Metadata
[source,json]
----
{
  "meta": {
    "href": "https://api.example.com/users/1"
  },
  "firstName": "Bob",
  "lastName": "Smith",
  "birthDate": "1980-01-23"
}
----

==== Example Collection Resources

An Ion collection resource is an Ion resource with:

1. a `collection` value in the `meta` object's `rel` (relation) array.
1. An `items` array.

An example Ion collection resource that does not currently reference other resources:

.Example Empty Ion Collection Resource:
[source,json]
----
{
  "meta": {
    "href": "https://api.example.com/users",
    "rel": ["collection"]
  },
  "offset": 0,
  "limit": 0,
  "size": 0,
  "first": { "meta": { "href": "https://api.example.com/users?offset=0", "rel": ["collection"] } },
  "previous": null,
  "next": null,
  "last": { "meta": { "href": "https://api.example.com/users?offset=0", "rel": ["collection"] } },
  "items": []
}
----

An example Ion collection resource with pagination support that represents the first
"page" of referenced resources:

.Example Paginated Ion Collection Resource:
[source,javascript]
----
{
  "meta": {
    "href": "https://api.example.com/users",
    "rel": ["collection"]
  },
  "offset": 0,
  "limit": 25,
  "size": 218,
  "first": { "meta": { "href": "https://api.example.com/users?offset=0", "rel": ["collection"] } },
  "previous": null,
  "next": { "meta": { "href": "https://api.example.com/users?offset=25", "rel": ["collection"] } },
  "last": { "meta": { "href": "https://api.example.com/users?offset=200", "rel": ["collection"] } },
  "items": [
    {
      "meta": {
        "href": "https://api.example.com/users/1"
      },
      "firstName": "Bob",
      "lastName": "Smith",
      "birthDate": "1977-04-18"
    },
    //... items 2-24 omitted for brevity
    {
      "meta": {
        "href": "https://api.example.com/users/25"
      },
      "firstName": "Jane",
      "lastName": "Doe",
      "birthDate": "1980-01-23"
    }
  ]
}
----

==== Example Links

An Ion link is a JSON serialization of a {uri-rfc5988}[web link] to another
resource. For example, assume that a user "Joe" is an employee of "Acme"
corporation.  A link within the "Joe" resource to Joe's employer might be
represented as follows:

.Ion Link from one resource to another:
[source,javascript]
----
"employer": {
  "meta": { "href": "https://api.example.com/corporations/acme"} }
}
----

=== Notational Conventions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described in Key
words for use in RFCs to Indicate Requirement Levels {uri-rfc2119}[RFC2119].  If
these words are used without being spelled in uppercase then they are
to be interpreted with their normal natural language meanings.


== Metadata

An Ion resource MAY contain a direct child _Meta Object_. If present,
the _Meta Object_ represents data about its immediate parent Ion resource.
The _Meta Object_ is OPTIONAL.

If a _Meta Object_ is present, the resource field name MUST equal the
case-sensitive octet sequence `meta` and the field value MUST be a non-null, non-empty
JSON object. A _Meta Object_ MUST contain one or more name/value
pairs. Ion parsers MUST reject Ion resources where a direct child `meta` field
exists and the field value is `null` or an empty JSON object.

The field names within a _Meta Object_ MUST be unique; Ion parsers MUST either
reject _Meta Object_ fields with duplicate field names or use a JSON
parser that returns only the lexically last duplicate field, as specified
in {uri-ecmaScript-5-1-15-12}[Section 15.12 (The JSON Object)] of {uri-ecmaScript-5-1}[ECMAScript 5.1].

The set of fields that a _Meta Object_ must contain to be considered valid
is resource-dependent.  In the absense of any resource-specific requirements,
any field not understood by implementations MUST be ignored.

=== Registered Metadata Field Names

The following field names are registered in the IANA Ion Metadata field registry
defined in [TBD].  None of the fields defined below are intended to be mandatory
in all cases, but rather, provide an initial set likely to be useful for common
use cases.

==== `href`

A resource's {uri-IRIs}[IRI] (Internationalized Resource Identifier).

A _Link_ MUST contain an `href` field.  A _Link_ `href` IRI is the location of
 the linked resource, called the "target IRI".

A _Meta Object_ MAY contain an OPTIONAL `href` field.  If present, the
_Meta Object_ `href` field IRI is the location of the parent resource, called
the "context IRI". It is RECOMMENDED that a _Meta Object_ always contain an
`href`.

Note that in the common case, target IRIs and context IRIs will also be
{uri-URIs}[URI]s (RFC 3986), because many protocols (such as HTTP) do not support
dereferencing IRIs.  In serializations that do not support IRIs, IRIs will be
converted to URIs according to {uri-IRIs-3-1}[RFC 3987, Section 3.1].

==== `mediaType`

A resource's https://tools.ietf.org/html/rfc6838[Media Type].  Use of this
Field is OPTIONAL.

==== `rel`

An array of IANA http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1[Link Relation Type]s.

A _Link_ MAY contain a `rel` field.  

A _Link_ to an ION collection resource MUST contain a `rel` field that has at least the `collection` relation specified.


== IANA Considerations

=== Ion Metadata Field Registry

This specification establishes the IANA Ion Metadata Field registry for Ion
Metadata Field Names.  The registry records the Field Name and a reference to
the specification that defines it.  This specification registers the Field Names
defined in Section 2.1.

Values are registered on a
{uri-IANA-consideration-guidelines}[specification required] (RFC 5226) basis
after a review period on the Ion Working Group (IWG)
https://github.com/ionwg/ion-doc[ion-doc GitHub repository], on the advice of
one or more Designated Experts. However, to allow
for the allocation of values prior to publication, the Designated Expert(s) may
approve registration once they are satisfied that such a specification will be
published.

Registration requests must filed as an
https://github.com/ionwg/ion-doc/issues[ion-doc GitHub issue] for review and
comment, with an appropriate subject (e.g., "Request to register metadata
field: example").

Within the review period, the Designated Expert(s) will either approve or deny
the registration request, communicating this decision by closing the issue.
Denials should include an explanation and, if applicable, suggestions as to
how to make the request successful.  Registration requests that are undetermined
for a period longer than 21 days can be brought to the IWG's attention using
@mentions in a new GitHub issue for resolution.

Criteria that should be applied by the Designated Expert(s) includes determining
whether the proposed registration duplicates existing functionality, determining
whether it is likely to be of general applicability or whether it is useful only
for a single application, and whether the registration description is clear.

IANA must only accept registry updates from the Designated Expert(s) and should
direct all requests for registration to the GitHub issue tracker.

It is suggested that multiple Designated Experts be appointed who are able to
represent the perspectives of different applications using this specification,
in order to enable broadly-informed review of registration decisions.  In cases
where a registration decision could be perceived as creating a conflict of
interest for a particular Expert, that Expert should defer to the judgment of
the other Expert(s).

Proposed registry description information:

* Protocol Category: Ion
* Registry Location: http://www.iana.org/assignments/ion
* Webpage Title: Ion
* Registry Name: Ion Metadata Fields

==== Registration Template

.Field Name:
The name requested (e.g., "href"). This name is case-sensitive.  Names may not
match other registered names in a case-insensitive manner unless the
Designated Expert(s) state that there is a compelling reason to allow an
exception in this particular case.

.Field Description
Brief description of the Field (e.g., "Resource IRI location").

.Change Controller:
For Standards Track RFCs, state "IESG".  For others, give the name of the
responsible party.  Other details (e.g., postal address, email address, home
page URI) may also be included.

.Specification Document(s):
Reference to the document(s) that specify the parameter, preferably including
URI(s) that can be used to retrieve copies of the document(s).  An indication
of the relevant sections may also be included but is not required.
