= The Ion Hypermedia Types
Les Hazlewood <les@hazlewood.com[@lhazlewood]>
2014-12-27
:revdate: 2014-12-27 14:07:33 -0800
:toc:
// URIs:
:uri-json: http://www.json.org
:uri-rest: http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm
:uri-rfc2119: https://tools.ietf.org/html/rfc2119
:uri-rfc5988: http://tools.ietf.org/html/rfc5988

draft-ionwg-ion-01

.Abstract

This document specifies Ion, a simple {uri-json}[JSON]-based content and
metadata hypermedia type suitable for {uri-rest}[REST] resource interchange.

.Status

This Internet-Draft is a working document of the Ion Working Group (IWG).  Note
that other groups may also distribute working documents as Internet-Drafts.

Internet-Drafts are draft documents valid for a maximum of six months
and may be updated, replaced, or obsoleted by other documents at any
time.  It is inappropriate to use Internet-Drafts as reference
material or to cite them other than as "work in progress."

This Internet-Draft will expire on 30 June 2015.

.Copyright Notice

Copyright (c) Les Hazlewood 2013-2015 and persons identified as document authors.
All rights reserved.

== Introduction

HTTP is commonly used to transfer data in many different data formats. With
the advent of the {uri-rest}[REST] architectural style, HTTP-enabled
applications often support {uri-json}[JSON] as data format for data exchange.
However, JSON's simple grammar can support virtually any data model - additional
context is required for machine HTTP clients and servers to interpret data and
metadata in important ways.

Ion exists to codify specific name/value pairs within a JSON document to better
facilitate JSON-based data and metadata exchange between HTTP clients and servers.
As such, Ion does not define a new data grammar - it is a
Media Subtype of `application/json`.

Ion defines the three following concepts in a JSON format:

1. _Instance Resource_: A JSON document that primarily represents a single
   resource and its metadata.
2. _Collection Resource_: A JSON document that represents a collection of other
   resources and the collection's metadata.
3. _Link_: A JSON-specific serialization of a {uri-rfc5988}[Web Link] that
   enables linking from one resource to another.

=== Media Type Name and Version

The Media Type name assigned for Ion Instance Resource documents is:

`application/ion+json`

The Media Type name assigned for Ion Collection Resource documents is:

`application/ionc+json`

For convenience, this data format may be referred to as "Ion 1.0".  This
specification uses "Ion" internally.

=== Examples

The following examples are non-normative.

==== Example Instance Resources

A single Ion instance resource without metadata is simply a standard JSON document:

.Ion Instance Resource Without Metadata
[source,json]
----
{
  "firstName": "Bob",
  "lastName": "Smith",
  "birthDate": "1980-01-23"
}
----

A single Ion instance resource with metadata is a JSON document that has a `meta`
name/value pair.

.Ion Instance Resource With Metadata
[source,json]
----
{
  "meta": {
    "href": "https://api.example.com/users/1"
  },
  "firstName": "Bob",
  "lastName": "Smith",
  "birthDate": "1980-01-23"
}
----

==== Example Collection Resources

An empty Ion collection resource that does not currently reference other
resources:

.Empty Ion Collection Resource:
[source,json]
----
{
  "meta": {
    "href": "https://api.example.com/users"
  },
  "offset": 0,
  "limit": 0,
  "size": 0,
  "first": { "meta": { "href": "https://api.example.com/users" } },
  "previous": null,
  "next": null,
  "last": { "meta": { "href": "https://api.example.com/users" } },
  "items": []
}
----

An Ion collection resource with pagination support that represents the first
'page' of referenced resources:

.Paginated Ion Collection Resource:
[source,javascript]
----
{
  "meta": {
    "href": "https://api.example.com/users"
  },
  "offset": 0,
  "limit": 25,
  "size": 218,
  "first": { "meta": { "href": "https://api.example.com/users" } },
  "previous": null,
  "next": { "meta": { "href": "https://api.example.com/users?offset=25" } },
  "last": { "meta": { "href": "https://api.example.com/users?offset=200" } },
  "items": [
    {
      "meta": {
        "href": "https://api.example.com/users/1"
      },
      "firstName": "Bob",
      "lastName": "Smith",
      "birthDate": "1977-04-18"
    },
    //... items 2-24 omitted for brevity
    {
      "meta": {
        "href": "https://api.example.com/users/25"
      },
      "firstName": "Jane",
      "lastName": "Doe",
      "birthDate": "1980-01-23"
    }
  ]
}
----

==== Example Links

An Ion link is a JSON serialization of a {uri-rfc5988}[web link] to another
resource. For example, assume that a user "Joe" is an employee of "Acme"
corporation.  A link from the "Joe" resource to Joe's employer might be
represented as follows:

.Ion Link from one resource to another:
[source,javascript]
----
{
   //other fields omitted for brevity...
   "firstName": "Joe",
   "employer": {
     "meta": { "href": "https://api.example.com/corporations/acme"} }
   }
}
----

=== Notational Conventions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described in Key
words for use in RFCs to Indicate Requirement Levels {uri-rfc2119}[RFC2119].  If
these words are used without being spelled in uppercase then they are
to be interpreted with their normal natural language meanings.
