= The Ion Hypermedia Type
The Ion Working Group
:revnumber: draft-ionwg-ion-01
:revdate: {docdatetime}
:source-highlighter: pygments
:toc: right
// URIs:
:uri-json: http://tools.ietf.org/html/rfc7159
:uri-rest: http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm
:uri-rfc2119: https://tools.ietf.org/html/rfc2119
:uri-rfc5988: http://tools.ietf.org/html/rfc5988
:uri-rfc5988-links: https://tools.ietf.org/html/rfc5988#section-3
:uri-rfc5988-linkRelType: https://tools.ietf.org/html/rfc5988#section-4
:uri-rfc7231-methods: https://tools.ietf.org/html/rfc7231#section-4.1
:uri-mediaType-namingReqs: https://tools.ietf.org/html/rfc6838#section-4.2
:uri-rfc-json-value: https://tools.ietf.org/html/rfc7159#section-3
:uri-linkRelType-item: http://tools.ietf.org/html/rfc6573#section-2.1
:uri-link-relation-types: http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1
:uri-ecmaScript-5-1: http://www.ecma-international.org/ecma-262/5.1
:uri-ecmaScript-5-1-15-12-2: http://www.ecma-international.org/ecma-262/5.1/#sec-15.12.2
:uri-IRIs: http://tools.ietf.org/html/rfc3987
:uri-IRIs-3-1: http://tools.ietf.org/html/rfc3987#section-3.1
:uri-URIs: http://tools.ietf.org/html/rfc3986
:uri-links: http://tools.ietf.org/html/rfc5988#section-3
:uri-IANA-consideration-guidelines: https://tools.ietf.org/html/rfc5226
:uri-semver: http://semver.org

An intuitive JSON-based hypermedia type for {uri-rest}[REST].

.Abstract

This document specifies the Ion Hypermedia Type, a simple and intuitive
{uri-json}[JSON]-based hypermedia type for {uri-rest}[REST].

.Status

This Internet-Draft is a working document of the Ion Working Group (IWG).  Note
that other groups may also distribute working documents as Internet-Drafts.

Internet-Drafts are draft documents valid for a maximum of six months
and may be updated, replaced, or obsoleted by other documents at any
time.  It is inappropriate to use Internet-Drafts as reference
material or to cite them other than as "work in progress."

This Internet-Draft will expire on 31 March 2017.

.Copyright Notice

Copyright (c) 2013-2017 Ion Working Group and persons identified as document authors.  All rights reserved.

:sectnums:

== Introduction

HTTP is commonly used to transfer data in many different data formats. With the advent of the {uri-rest}[REST]
architectural style and the success of the JavaScript programming language, HTTP-enabled applications regularly
support {uri-json}[JSON] as a preferred format for data exchange.

However, this poses a challenge for machine data exchange at web scale across heterogeneous domains and organizations;
JSON's simple grammar can support virtually any data model - additional context is required for machine clients and
servers to automate information discovery and exchange via hypermedia controls.

Ion codifies specific name/value pairs within JSON objects to help automate JSON-based hypermedia interchange between
machines.  And while machine data and metadata interchange is the primary goal, Ion's second most important design
goal is to enable intuitive and context-relevant structure so Ion content is very easy to understand for humans, even
if they may not know what Ion is.

=== Terminology

These terms are defined by this specification:

.Member
A JSON name/value pair as defined in https://tools.ietf.org/html/rfc7159#section-4[RFC 7159].

.Root Object
The single JSON object at the root of an Ion content structure.

.Value Object
A JSON object with a member named `value`.

.Collection Object
A _Value Object_ where the `value` member is a JSON array.  If a JSON value is an element in a _Collection Object_'s
`value` array, it is said that the Collection Object _contains_ that value.

.Resource
The referent of an {uri-IRIs}[International Resource Identifier].

.Collection Resource
A _Resource_ that is also a _Collection Object_.

.Link
A JSON object with an {uri-IRIs}[IRI] member named `href`.  This is Ion's JSON serialization of a {uri-links}[Web Link]
that enables linking from one resource to another.

.Form Field
A JSON object with members that describe a named value that may be collected and submitted to a linked resource location.

.Form Field Option
A _Value Object_ with a `value` that may be applied to the containing Form Field's `value`.

.Form
An _Collection Object_ where the `value` array member contains Form Fields.

.Linked Form
A _Form_ that is also a _Link_.  Form data submitted will be sent to the form's `href` resource location.

=== Media Type Name and Version

The Media Type name assigned for Ion content is:

`application/ion+json`

This format may be referred to as "Ion 1.0". This specification uses "Ion" internally.

Any future version will be represented with a media type parameter named `v` with a {uri-semver}[semantic version]
value.  For example (non-normative):

`application/ion+json;v=2`

=== Examples

All following examples are non-normative.

==== Example Objects

JSON objects are parsed as as expected:

.Example JSON Object
[source,json]
----
{
  "firstName": "Bob",
  "lastName": "Smith",
  "birthDate": "1980-01-23"
}
----

A _Value Object_ is a JSON object with a `value` member:

.Example Value Object
[source,json]
----
{
  "value": "Hello"
}
----

A _Value Object_ exists to represent a primary JSON value, but it also might have other members that are contextually
relevant to the value.  For example, one might add a `lang` member to indicate a spoken language:

.Example Value Object With Supporting Members
[source,json]
----
{
  "value": "Hello",
  "lang": "en"
}
----

==== Example Links

An Ion _Link_ is a JSON object that contains an {uri-IRIs}[IRI] member named `href`.  An Ion Link is a JSON
serialization of a {uri-rfc5988}[web link] to another resource.

For example, assume that someone named "Joe" is an employee of the "Acme" corporation.  A link within the "Joe"
resource to Joe's employer might be represented as follows:

.Ion Link from one resource to another:
[source,json]
----
{
  "name": "Joe",
  "employer": { "href": "https://example.io/corporations/acme" }
}
----

==== Example Collections

A _Collection Object_ is a _Value Object_ where the `value` member is a JSON array:

.Example Empty Collection Object:
[source,json]
----
{
  "value": []
}
----

What's the point of this?  Why not just use a JSON array directly?

The reason is that other members within the Collection Object may provide additional contextual information about
the `value` array itself or the elements in the `value` array, something not possible with a direct array.

For example, a _Collection Object_ could have an `itemtype` property to represent an application-defined data type that
should be associated with each element in the `value` array instead of repeating this information in every array
element:

.Example Collection Object With element metadata:
[source,json]
----
{
  "itemtype": "person",
  "value": [
      {
        "firstName": "Bob",
        "lastName": "Smith",
      },
      {
        "firstName": "Jane",
        "lastName": "Doe",
      }
    ]
}
----

Collection Objects can have other members to build up rich functionality.  For example,
one can add link members to represent a Collection Object as an IRI-accessible _Collection Resource_:

.Example Empty Collection Resource:
[source,json]
----
{
  "self": { "href": "https://example.io/users", "rel": ["collection"] },
  "value": []
}
----

More members can be added to build up rich functionality.  For example, a Collection Resource with
discoverable pagination:

.Example Paginated Collection Resource:
[source,javascript]
----
{
  "self": { "href": "https://example.io/users", "rel": ["collection"] },
  "desc": "Showing 25 of 218 users.  Use the 'next' link for the next page.",
  "offset": 0,
  "limit": 25,
  "size": 218,
  "first": { "href": "https://example.io/users", "rel": ["collection"] },
  "previous": null,
  "next": { "href": "https://example.io/users?offset=25", "rel": ["collection"] },
  "last": { "href": "https://example.io/users?offset=200", "rel": ["collection"] },
  "value": [
    {
      "self": { "href": "https://example.io/users/1" },
      "firstName": "Bob",
      "lastName": "Smith",
      "birthDate": "1977-04-18"
    },
    //... items 2-24 omitted for brevity
    {
      "self": { "href": "https://example.io/users/25" },
      "firstName": "Jane",
      "lastName": "Doe",
      "birthDate": "1980-01-23"
    }
  ]
}
----

==== Example Form

An Ion Form is a _Collection Object_ where the `value` member array contains _Form Fields_.  Ion Forms ensure
that resource transitions (links) that support data submissions can be discovered automatically (colloquially
referred to as https://en.wikipedia.org/wiki/HATEOAS[HATEOAS]).

.Example Ion Form
[source,json]
----
{
  "href": "https://example.io/users", "rel":["create-form"], "method": "POST",
  "value": [
    { "name": "username" },
    { "name": "password", "secret": true },
    { "name": "favoriteColor", "label": "Favorite Color", "options": {
        "value": [
          { "label": "Red", "value": "red" },
          { "label": "Blue", "value": "blue" }
        ]
      }
    },
    { "name": "visitedContinents", "type": "set", "minitems": 1, "maxitems": 7, "options": {
        "value": [
          { "label": "Africa", "value": "af" },
          { "label": "North America", "value": "na" },
          { "label": "South America", "value": "sa" },
          { "label": "Europe", "value": "eu" },
          { "label": "Asia", "value": "as" }
          { "label": "Oceania", "value": "oc" }
          { "label": "Antarctica", "value": "an" }
        ]
      }
    },
    { "name": "favoriteContinent", "options": {
        "value": [
          { "label": "Africa", "value": "af" },
          { "label": "North America", "value": "na" },
          { "label": "South America", "value": "sa" },
          { "label": "Europe", "value": "eu" },
          { "label": "Asia", "value": "as" }
          { "label": "Oceania", "value": "oc" }
          { "label": "Antarctica", "value": "an" }
        ]
      }
    }
  ]
}
----

=== Notational Conventions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described {uri-rfc2119}[RFC2119] when they appear in UPPERCASE.
If these words are used without being spelled in uppercase then they are to be interpreted with their normal natural
language meanings, without any normative meaning.


[[content-structure]]
== Content Structure

Ion content MUST use UTF-8 encoding.  Other encodings MUST NOT be used.

Ion content MUST have exactly one root JSON object, called the _Root Object_.  The Root Object MAY contain
name/value pairs called 'members' and any level of nested JSON objects.

[[valueobjects]]
== Value Objects

A _Value Object_ is a JSON object that contains a `value` member.

A _Value Object_ is used to represent a primary JSON value but also allows for other peer members to provide additional
contextual information or metadata regarding the `value` member.

An Ion parser MUST identify a JSON object as a _Value Object_ if the JSON object contains a JSON member with a name
equal to the case-sensitive octet sequence `value`.

A _Value Object_ MAY have additional members other than the `value` member.

The member names within an identified _Value Object_ SHOULD be unique; Ion parsers MUST either reject _Value Object_
members with duplicate member names or use a JSON parser that returns only the lexically last duplicate member, as
specified in {uri-ecmaScript-5-1-15-12-2}[Section 15.12.2 (The JSON Object - parse)] of {uri-ecmaScript-5-1}[ECMAScript 5.1].

A _Value Object_ MAY contain members that are not defined in the Ion Object Member Registry.  Any member not
understood by an Ion parser SHOULD be ignored.

Consider the following non-normative example of an object with a `greeting` member:

.Example object with a greeting:
[source,json]
----
{
  "greeting": "Hola"
}
----

In this example, the `greeting` member value is a Spanish language word.  A _Value Object_ might be used instead to
represent additional contextual information that might be relevant to user agents.  For example:

.Example object with a greeting value object:
[source,json]
----
{
  "greeting" : { "value":  "Hola", "lang": "es" }
}
----

In this example, the `greeting` member transitively reflects reflects a value of `Hola` through the presence of
a _Value Object_.

[[links]]
== Links

An Ion Link is a a JSON object that contains an {uri-IRIs}[IRI] member named `href`. An Ion Link is a JSON
serialization of a {uri-rfc5988}[web link] to another resource.

An Ion parser MUST identify a JSON object as an _Ion Link_ if the object contains an {uri-IRIs}[IRI] member with a
name equal to the case-sensitive octet sequence `href`.

If the `href` member value is `null`, not a string, an empty string, or a whitespace-only (blank) string, an Ion parser MUST NOT identify the object as an _Ion Link_.

An _Ion Link_ MAY have additional members other than the `href` member.

A non-normative example of a minimal Ion link:

.Example simplest Ion link:
[source,json]
----
{ "href": "https://example.io/corporations/acme" }
----

A non-normative example of an Ion Link that is also a Value Object:

.Example Ion Link that is also a Value Object:
[source,json]
----
{
  "href": "https://example.io/corporations/acme",
  "value": "Acme, Inc."
}
----

=== Link Relation Types

All Ion links have one or more {uri-link-relation-types}[Link Relation Types].  A link's total set of link relation
types is the set union of the link's implicit link relation type and the link's explicit link relation types.

==== Implicit Link Relation Type

All Ion links have exactly one implicit link relation type.  The implicit link relation type can be one of three
possible values depending on where the link is located in the Ion content:

1. Root Object
2. Named Link
3. Collection Object `value` array element

===== Root Object Implicit Link Relation Type

If the Root Object is also found to be an Ion Link, it has an implicit link relation type of `self`.

A non-normative example of a Root Object that is also an Ion Link:

[source,json]
----
{
  "href": "https://example.io/users/1",
  "name": "Joe"
}
----

===== Named Link Implicit Link Relation Type

If a JSON Object member value is an Ion Link, the Ion Link is implicitly assigned a link relation type that equals the member name.

A non-normative example:

[source,json]
----
{
  "employer": { "href": "https://example.io/corporations/acme" }
}
----

The above example shows an Ion Link member named `employer`.  The octet sequence `employer` is therefore assigned as the link's implicit link relation type.

===== Collection Item Implicit Link Relation Type

Any Ion Link in a _Collection Object_'s `value` array is implicitly assigned the {uri-linkRelType-item}[`item`] link
relation type.

A non-normative example:

[source,json]
----
{
  "self": { "href": "https://example.io/users", "rel": ["collection"] },
  "value": [
    { "href": "https://example.io/users/1" },
    { "href": "https://example.io/users/2" }
  ]
}
----

The above example has 2 Links in its `value` array.  Each of these 2 links are implicitly assigned the
{uri-linkRelType-item}[`item`] link relation type.

==== Explicit Link Relation Types

An Ion Link MAY have one or more explicitly defined link relation types declared as an array of strings assigned to the link Meta Object's `rel` member.

A non-normative example of a link with an explicitly defined link relation type:

.Example Ion Link with explicit link relation type:
[source,json]
----
{ "href": "https://cdn.example.com/example.ico", "rel": ["icon"] }
----

The above example has an explicit link relation type of http://www.w3.org/TR/html5/links.html#rel-icon[`icon`].

More than one explicit link relation type MAY be defined in the `rel` array.

Ion parsers MUST ignore any Link `rel` member with value of `null`, not a string, an empty string, or a whitespace-only (blank) string.

[[forms]]
== Forms

If data can be submitted to a linked resource location, information about that data must be made available to a
hypermedia client so it can collect and then submit the data.

An Ion Form represents named data values that may be submitted to a linked resource location. A JSON object of members
that describe each named data value is called a _Form Field_.  An Ion Form is then effectively a collection of form
 fields with additional metadata that controls how the form fields are submitted to a linked resource location.

If an Ion Form is also an Ion Link, collected data associated with the form's fields may be submitted to the Form's
linked resource location.

An Ion Form _may not_ be an Ion Link if and only if that form is nested inside another form or form field.  Nesting forms
allows for creation of complex object graphs that may be submitted to the top-most form's linked resource location.

An Ion Form MUST also be an Ion Link if it is not nested within another form.

[[form-structure]]
=== Form Structure

Ion parsers MUST identify any JSON object as an Ion Form if the object matches the following conditions:

1. Either:
  a. The JSON object is discovered to be an Ion Link as defined in <<links, Section 4>> AND its `meta` member has
     an internal `rel` member that contains one of the octet sequences `form`, `edit-form`, `create-form` or
     `query-form`, OR:
  b. The JSON object is a member named `form` inside an Ion Form Field.
2. The JSON object has a `value` array member with a value that is not `null` or empty.
3. The JSON object's `value` array contains one or more Ion Form Field objects.
4. The JSON object's `value` array does not contain elements that are not Ion Form Field objects.

Ion parsers MUST NOT identify a JSON object as an Ion Form if the object does not match the above conditions.

A non-normative example:

[source,json]
----
{
  "href": "https://example.io/loginAttempts", "rel":["form"], "method": "POST",
  "value": [
    { "name": "username" },
    { "name": "password", "secret": true }
  ]
}
----

[[form-fields]]
=== Form Fields

An Ion Form Field is a JSON object in an Ion Form's `value` array that contains one or more
<<form-field-members, Form Field Members>>.

An Ion Form Field MUST have a string member named `name`.

Each Ion Form Field within an Ion Form's `value` array MUST have a unique `name` value compared to any other Form Field
within the same array.

[[form-field-members]]
=== Form Field Members

An Ion Form Field has one or more of the following members.

==== `desc`

The `description` member is a string description of the field that may be used to enhance usability, for example, as
a tool tip.

Use of this member is OPTIONAL.

==== `enabled`

The `enabled` member indicates whether or not the field `value` may be modified or submitted to a linked resource location.

The `enabled` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `false` value indicates that the field value MUST NOT be modified or submitted to a linked resource location.

If the `enabled` member is not present, or if it present and equal to `true`, the field may be modified or submitted a linked resource location.

If a field should be considered enabled, it is RECOMMENDED to omit the `enabled` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

==== `form`

The `form` member value is either a Form object or a Link to a Form object that reflects the required object structure
of the Field `value`. This allows Ion content authors to define complex data/content graphs that may be
submitted to a single linked resource location.

Ion parsers MUST ignore a discovered `form` member if the field `type` member does not equal `object`.

If the `form` member is a Link or a Linked Form, Ion parsers MUST NOT submit data to the `form` value's linked
`href` location.  The form's `href` location may only be used to read the associated form to
determine the structure of the associated value object.

Where a Form contains nested Forms in this manner, the resulting collected data will form an object graph.  This
data/graph may only be submitted to the top-most Form's linked resource location; Ion parsers MUST NOT submit data to
any nested/child Form linked resource location.

==== `itemtype`

The `itemtype` member specifies the mandatory data type that each value in a `value` array must adhere to. If present,
the `itemtype` member value MUST equal one of the octet sequences defined in
<<Form Field `type` Values, Form Field `type` Values>>.

If the `type` member is not equal to `array` or `set`, an Ion parser MUST ignore the `itemtype` member.

If the `type` member equals `array` or `set` and the `itemtype` member is present, an Ion parser MUST validate any
value in the `value` array to ensure it adheres to the specified type.

If the `type` member equals `array` or `set` and the `itemtype` member is not present or equals `null`, an Ion parser
MUST NOT perform type validation on any value in the array before submitting the `value` to a linked resource location.

Use of this member is OPTIONAL.

==== `label`

The `label` member is a human-readable string that may be used to enhance usability.

Use of this member is OPTIONAL.

==== `max`

The `max` member indicates that the field `value` must be less than or equal to the specified `max` value.

The `max` member value MUST conform to the data type defined by the `type` member value; Ion parsers MUST ignore
any `max` member where the `max` value does not conform to the `type` data type.

The `max` member value may only be defined when the `type` value is equal to `number`, `integer`, `decimal`, `date`,
`datetime`, `datetimetz`, `time`, or `timetz` as defined in <<Form Field `type` Values, Form Field `type` Values>>.  Ion
parsers MUST ignore any `max` member if the `type` member value does not match one of these values.

If the `min` member is present, the `max` value must be greater than or equal to the `min` value.  Ion parsers
MUST ignore both the `min` member and the `max` member if the `max` value is less than the `min` value.

Use of this member is OPTIONAL.

==== `maxitems`

The `maxitems` member value is a non-negative integer that specifies the maximum number of field values that may be
submitted when the field `type` value equals `array` or `set`.  Ion parsers MUST ignore any `maxitems` member that has
a negative integer value.

If the field `type` value does not equal `array` or `set`, an Ion parser MUST ignore any discovered `maxitems` member
for that field.

If a field has both `minitems` and `maxitems` members, the field's `maxitems` member value MUST be greater than or
equal to the field's `minitems` member value.  Ion parsers MUST ignore both the `minitems` and `maxitems` members if the
`maxitems` value is less than the `minitems` value.

Use of this member is OPTIONAL.

==== `maxlength`

The `maxlength` member is a non-negative integer that specifies the maximum number of characters the field `value`
may contain.  Ion parsers MUST ignore any `maxlength` member that has a negative integer value.

Ion parsers MUST ignore any discovered `minitems` member if the field `type` equals `object`, `array`, or `set`.

If a field has both `minlength` and `maxlength` members, the field's `minlength` member value MUST be less than or
equal to the field's `maxlength` member value.  Ion parsers MUST ignore both the `minlength` and `maxlength` members
if the `maxlength` value is less than the `minlength` value.

Use of this member is OPTIONAL.

==== `min`

The `min` member indicates that the field `value` must be greater than or equal to the specified `min` value.

The `min` member value MUST conform to the data type defined by the `type` member value; Ion parsers MUST ignore
any `min` member where the `min` value does not conform to the `type` data type.

The `min` member value may only be defined when the `type` value is `number`, `integer`, `decimal`, `date`,
`datetime`, `datetimetz`, `time`, or `timetz` as defined in <<Form Field `type` Values, Form Field `type` Values>>.  Ion
parsers MUST ignore any `min` member if the `type` member value does not match one of these values.

If the `max` member is present, the `min` value must be less than or equal to the `max` value.  Ion parsers
MUST ignore both the `min` member and the `max` member if the `min` value is greater than the `max` value.

Use of this member is OPTIONAL.

==== `minitems`

The `minitems` member value is a non-negative integer that specifies the minimum number of field values that may be
submitted when the field `type` value equals `array` or `set`.  Ion parsers MUST ignore any `minitems` member that has
a negative integer value.

If the field `type` value does not equal `array` or `set`, an Ion parser MUST ignore any discovered `minitems` member
for that field.

If a field has both `minitems` and `maxitems` members, the field's `minitems` member value MUST be less than or
equal to the field's `maxitems` member value.  Ion parsers MUST ignore both the `minitems` and `maxitems` members if the
`minitems` value is greater than the `maxitems` value.

Use of this member is OPTIONAL.

==== `minlength`

The `minlength` member is a non-negative integer that specifies the minimum number of characters the field `value`
must contain.  Ion parsers MUST ignore any `minlength` member that has a negative integer value.

Ion parsers MUST ignore any discovered `minlength` member if the field `type` equals `object`, `array`, or `set`.

If a field has both `minlength` and `maxlength` members, the field's `minlength` member value MUST be less than or
equal to the field's `maxlength` member value.  Ion parsers MUST ignore both the `minlength` and `maxlength` members
if the `minlength` value is greater than the `maxlength` value.

Use of this member is OPTIONAL.

==== `mutable`

The `mutable` member indicates whether or not the field value may be modified before it is submitted to the form's linked resource location.

The `mutable` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `false` value indicates that the field value MUST NOT be modified before it is submitted to the form's linked resource location.

If the `mutable` member is not present, or if it present and equal to `true`, the field value may be modified before it is submitted to the form's linked resource location.

If a field should be considered mutable, it is RECOMMENDED to omit the `mutable` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

==== `name`

The `name` member is a string name assigned to the field.

The `name` value MUST NOT be `null`.

The `name` value MUST NOT contain only whitespace.

The `name` value MUST be unique compared to any other Form Field `name` value in the containing Form's `value` array.

Use of this member is REQUIRED.

==== `options`

The `options` member is a Collection Object where the `value` array contains _Form Field Option_ objects.  A Form Field
Option object contains one or more members defined in <<form-field-option-members,Form Field Option Members>>.

When an `options` member is present, the form field `value` MUST be restricted to contain only values found within
Option `value` members.

If a field allows a single value and does not define a `type` member, an Ion parser MUST default the field `type` to be
equal to the type discovered by inspecting the first Option's `value` member value.

For example, consider the following form field:

.Example Form Field with Options (non-normative):
[source,json]
----
{ "name": "favoriteContinent", "options": {
    "value": [
      { "label": "Africa", "value": "af" },
      { "label": "North America", "value": "na" },
      { "label": "South America", "value": "sa" },
      { "label": "Europe", "value": "eu" },
      { "label": "Asia", "value": "as" }
      { "label": "Oceania", "value": "oc" }
      { "label": "Antarctica", "value": "an" }
    ]
  }
}
----

In this example, the field `value` may only have a single value (because the field `type` is not `array` or `set`),
and the `value`, if set, must equal one of the option values of `af`, `na`, `sa`, `eu`, `as`, `oc`, or `an` as defined
by the child Option `value` members.  Also, because this field does not define a `type` member, the field `type`
defaults to `string` because the first Option's `value` type (in this case `af`) is a `string`.

If the field `type` is `set` or `array`, then multiple values may be set for the field `value` in accordance with any
other applicable constraints.

If a field that allows multiple values does not define an `itemtype` member, an Ion parser MUST default the field
`itemtype` to be equal to the type discovered by inspecting the first Option's `value` member value.

For example, consider another form field that allows multiple values:

.Example Form Field with multiple Options (non-normative):
[source,json]
----
{ "name": "visitedContinents", "type": "set", "minitems": 1, "maxitems": 7, "options": {
    "value": [
      { "label": "Africa", "value": "af" },
      { "label": "North America", "value": "na" },
      { "label": "South America", "value": "sa" },
      { "label": "Europe", "value": "eu" },
      { "label": "Asia", "value": "as" }
      { "label": "Oceania", "value": "oc" }
      { "label": "Antarctica", "value": "an" }
    ]
  }
}
----

In this example, form field `value` may only be a `set` that contains a minimum of one value and a maximum of seven
values.  Because this field does not define an `itemtype` member, the `itemtype` defaults to `string` because the first
Option's `value` type (in this case `af`) is a `string`.

==== `pattern`

The `pattern` member is a JSON string that defines a regular expression used to validate the field `value`.

If specified, the `pattern` member string value must conform to the `Pattern` grammar defined in
https://www.ecma-international.org/ecma-262/5.1/#sec-15.10.1[Ecma-262 Edition 5.1 Section 15.10.1].

The `pattern` member MUST NOT be specified on fields with non-string or non-date/non-time value types.

Use of this member is OPTIONAL.

==== `placeholder`

The `placeholder` member is a short hint string that describes the expected field `value`.

Use of this member is OPTIONAL.

==== `required`

The `required` member indicates whether or not the field value may equal `null` before is submitted to the form's linked resource location.

The `required` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `true` value indicates that the field value MUST NOT equal `null` before it is submitted to the form's linked resource location.

If the `required` member is not present, or if it present and equal to `false`, the field value MAY equal `null` before it is submitted to the form's linked resource location.

If a field should not be considered required (i.e. optional), it is RECOMMENDED to omit the `required` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

==== `secret`

The `secret` member indicates whether or not the field value is considered sensitive information and should be kept
secret.

The `secret` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `true` value indicates that the field value is considered sensitive and should be kept secret.  If `true`, user
agents MUST mask the value so it is not directly visible to the user.

If the `secret` member is not present, or if it present and equal to `false`, the field value is not considered
sensitive information and does not need to be kept secret.

If a field should not be considered secret, it is RECOMMENDED to omit the `secret` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

==== `type`

The `type` member specifies the mandatory data type that the `value` member value must adhere to.  The `type` value is
a string and must equal to one of the octet sequences defined in <<Form Field `type` Values, Form Field `type` Values>>.

If the `type` member is not present, an Ion parser MUST assume a default `type` of `string` for the field.

An Ion parser MUST validate the `value` member value to ensure it adheres to the specified (or default) type.

Use of this member is OPTIONAL.

==== `value`

The `value` member reflects the value assigned to the field.

If the `type` member exists and does not equal `array` or `set, the `value` member value MUST conform to the data type
specified by the `type` member value.

If the `type` member exists and is equal to `array` or `set`, the `value` member value MUST be a JSON array.

Use of this member is OPTIONAL.

==== `visible`

The `visible` member indicates whether or not the field should be made visible by a user agent.  Fields that are not visible are usually used to retain a default value that must be submitted to the form's linked resource location.

The `visible` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `false` value indicates that the field MUST NOT be made visible by a user agent.

If the `visible` member is not present, or if it present and equal to `true`, the field MUST be made visible by a user agent.

If a field should be considered visible, it is RECOMMENDED to omit the `visible` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

[[form-field-type-values]]
=== Form Field `type` Values

A Form Field `type` member value MUST equal one of the following string literal values.

==== `array`

A non-null field `value` must be a JSON array.

If an `array` field also contains `min`, `minlength`, `max`, `maxlength` or `pattern` members, those
members' validation rules apply to each item in the array, not the array itself.

If an `array` field also declares an `options` member, the array MUST NOT contain any value that does not appear in a
nested `option` `value` member.

==== `binary`

A non-null field `value` must be a JSON string that is a `base64Url`-encoded octet sequence according to https://tools.ietf.org/html/rfc4648#section-5[RFC 4648, Section 5].  The string MUST NOT contain characters that are not in the `base64Url` alphabet.

==== `boolean`

A non-null field `value` must be a JSON boolean.

==== `date`

A non-null field `value` must be a JSON string that conforms to the `full-date` grammar defined in https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

==== `datetime`

A non-null field `value` must be a JSON string that conforms to the `date-time` grammar defined in https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

==== `decimal`

A non-null field `value` must be a JSON number that contains a decimal point (aka the Period `.` character, ASCII code 46).

==== `duration`

A non-null field `value` must be a JSON string that conforms to the `duration` grammar defined in https://tools.ietf.org/html/rfc3339#appendix-A[RFC 3339 Appendix A].

==== `email`

A non-null field `value` must be a JSON string that is also a valid email address as defined in https://www.ietf.org/rfc/rfc2822.txt[RFC 2822, Section 3.4].

==== `integer`

A non-null field `value` must be a JSON number that does not contain a decimal point (aka the Period `.` character, ASCII code 46).

==== `iri`

A non-null field `value` must be a JSON string that is a validly-formed Internationalized Resource Identifier (IRI) as defined by https://tools.ietf.org/html/rfc3987[RFC 3987].

==== `link`

A non-null `value` must be an Ion Link.

==== `number`

A non-null `value` must be a JSON number.

==== `object`

A non-null `value` must be a JSON object.

If the field has a `form` member, the field `value` JSON object MUST be the JSON representation that would result if
submitting that form.

==== `pdatetime`

A non-null field `value` must be a partial datetime (a datetime without a timezone) which is a JSON string that
conforms to the following https://tools.ietf.org/html/rfc5234[ABNF] grammar:

    pdatetime = full-date "T" partial-time

where `full-date` and `partial-time` are defined in https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

To avoid potential logic inconsistencies across heterogeneous systems, it is RECOMMENDED to use `datetime` instead of `pdatetime` when possible.

==== `ptime`

A non-null field `value` must be a partial time (a time without a timezone) which is a JSON string that conforms to
the `partial-time` grammar defined in https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

To avoid potential logic inconsistencies across heterogeneous systems, it is RECOMMENDED to use `time` instead of `ptime` when possible.

==== `set`

The field `value` must be a JSON array and the array MUST NOT contain any element that is equal to any other
element within the same array, where element equality is defined in Appendix A.

If a `set` field also contains `min`, `minlength`, `max`, `maxlength` or `pattern` members, those
members' validation rules apply to each item in the set array, not the set array itself.

If a `set` field also declares an `options` member, the set array MUST NOT contain any value that does not appear in a
nested `option` `value` member.

==== `string`

A non-null field `value` must be a JSON string.

==== `time`

A non-null field `value` must be a JSON string that conforms to the `full-time` grammar defined in
https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339 Section 5.6].

==== `url`

A non-null field `value` must be a JSON string that is a validly-formed Uniform Resource Locator (URL) as defined by
https://tools.ietf.org/html/rfc3986#section-1.1.3[RFC 3986 Section 1.1.3].

[[form-field-option-members]]
=== Form Field Option Members

An Form Field Option has one or more of the following members.

==== `enabled`

The `enabled` member indicates whether or not the Option `value` may be applied to the containing Form Field's `value`.

The `enabled` member is a boolean; it must equal either `true` or `false`. `null` or any other JSON value MUST NOT be specified.

A `false` value indicates that the Option `value` MUST NOT be applied to the containing Form Field's `value`.

If the `enabled` member is not present, or if it present and equal to `true`, the Option `value` may be applied to the containing Form Field's `value`.

If an Option should be considered enabled, it is RECOMMENDED to omit the `enabled` member entirely to reduce verbosity.

Use of this member is OPTIONAL.

==== `label`

The `label` member is a human-readable string that may be used to enhance usability.

Use of this member is OPTIONAL.

==== `value`

The `value` member reflects the value assigned to the Option. An enabled Option that is selected will have its `value`
applied to the containing Form Field's `value` member.

Use of this member is REQUIRED.

== Registered Ion Object Member Names

The following member names are registered in the IANA Ion Object Member Registry
defined in [TBD].  None of the members defined below are intended to be mandatory
in all cases, but rather, provide an initial set likely to be useful for common
use cases.

=== `href`

The `href` (hypermedia reference) member identifies the target {uri-IRIs}[IRI] (Internationalized Resource Identifier) location of the resource. The `href` value is a case-sensitive {uri-IRIs}[IRI] value.

If an `href` member exists, Ion parsers MUST identify the containing JSON Object as an Ion Link in addition to any other Ion Object identified.

Note that in the common case, target IRIs and context IRIs will also be
{uri-URIs}[URI]s (RFC 3986), because many protocols (such as HTTP) do not support
dereferencing IRIs.  In serializations that do not support IRIs, IRIs will be
converted to URIs according to {uri-IRIs-3-1}[RFC 3987 Section 3.1].

Use of this member is OPTIONAL.

=== `method`

The `method` member identifies the {uri-rfc7231-methods}[HTTP method] to be used when sending an HTTP request to the associated `href` resource location.  The `method` value is a case-sensitive string as defined by {uri-rfc7231-methods}[RFC 7231 Section 4.1] and safety and idempotent semantics are equivalent to those specified in RFC 7231.

If an `href` member is defined and a peer `method` member is not defined, or the `method` member value is null or not recognized, HTTP `GET` MUST be used if an HTTP request is made to the linked resource.

Use of this member is OPTIONAL.

=== `accepts`

The `accepts` member identifies one or more supported representation https://tools.ietf.org/html/rfc6838[Media Type] that may be submitted to the associated `href` resource location. The value is a JSON array of strings.  Each string in the array MUST be a case-insensitive string as defined by {uri-mediaType-namingReqs}[RFC 6838 Section 4.2].

An HTTP user agent may submit an associated representation that conforms to any of these media types.  If submitting a representation, that representation's media type MUST be specified in the HTTP request https://tools.ietf.org/html/rfc7231#section-3.1.1.5[`Content-Type` header] value as defined by https://tools.ietf.org/html/rfc7231#section-3.4[RFC 7321 Section 3.4. Content Negotiation].

Use of this member is OPTIONAL.

=== `produces`

The `produces` member identifies one or more HTTP response representation https://tools.ietf.org/html/rfc6838[Media Type]s that may be returned from the associated `href` resource location.  The value is a JSON array of strings.  Each string in the array MUST be a case-insensitive string as defined by {uri-mediaType-namingReqs}[RFC 6838 Section 4.2].

An HTTP server may return a response body that conforms to any of these media types; the exact media type will be specified in the HTTP response https://tools.ietf.org/html/rfc7231#section-3.1.1.5[`Content-Type` header] as defined by https://tools.ietf.org/html/rfc7231#section-3.4[RFC 7321 Section 3.4. Content Negotiation].

Use of this member is OPTIONAL.

=== `rel`

The `rel` member identifies one or more explicit http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1[Link Relation Type]s assigned to an Ion Link.  The value is a JSON array of strings.  Each string MUST conform to the `relation-type` grammar definition in https://tools.ietf.org/html/rfc5988#section-5[RFC 5988 Section 5].

Use of this member is OPTIONAL.

A _Link_ to a _Ion Collection_ SHOULD contain a `rel` member that has at least the `collection` relation specified.

== IANA Considerations

=== Ion Object Member Registry

This specification establishes the IANA Ion Object Member Registry for Ion
Object Member Names.  The registry records the Member Name and a reference to
the specification that defines it.  This specification registers the Member Names
defined in Section 6.

Values are registered on a
{uri-IANA-consideration-guidelines}[specification required] (RFC 5226) basis
after a review period on the Ion Working Group (IWG)
https://github.com/ionwg/ion-doc[ion-doc GitHub repository], on the advice of
one or more Designated Experts. However, to allow
for the allocation of values prior to publication, the Designated Expert(s) may
approve registration once they are satisfied that such a specification will be
published.

Registration requests must filed as an
https://github.com/ionwg/ion-doc/issues[ion-doc GitHub issue] for review and
comment, with an appropriate subject (e.g., "Request to register value object
member: example").

Within the review period, the Designated Expert(s) will either approve or deny
the registration request, communicating this decision by closing the issue.
Denials should include an explanation and, if applicable, suggestions as to
how to make the request successful.  Registration requests that are undetermined
for a period longer than 21 days can be brought to the IWG's attention using
@mentions in a new comment appended to the GitHub issue for resolution.

Criteria that should be applied by the Designated Expert(s) includes determining
whether the proposed registration duplicates existing functionality, determining
whether it is likely to be of general applicability or whether it is useful only
for a single application, and whether the registration description is clear.

IANA must only accept registry updates from the Designated Expert(s) and should
direct all requests for registration to the https://github.com/ionwg/ion-doc/issues[Ion issue tracker].

It is suggested that multiple Designated Experts be appointed who are able to
represent the perspectives of different applications using this specification,
in order to enable broadly-informed review of registration decisions.  In cases
where a registration decision could be perceived as creating a conflict of
interest for a particular Expert, that Expert should defer to the judgment of
the other Expert(s).

Proposed registry description information:

* Protocol Category: Ion
* Registry Location: http://www.iana.org/assignments/ion
* Webpage Title: Ion
* Registry Name: Ion Object Members

==== Registration Template

.Member Name:
The name requested (e.g., "href"). This name is case-sensitive.  Names may not
match other registered names in a case-insensitive manner unless the
Designated Expert(s) state that there is a compelling reason to allow an
exception in this particular case.

.Member Description
Brief description of the Member (e.g., "Resource target IRI location").

.Change Controller:
For Standards Track RFCs, state "IESG".  For others, give the name of the
responsible party.  Other details (e.g., postal address, email address, home
page URI) may also be included.

.Specification Document(s):
Reference to the document(s) that specify the parameter, preferably including
URI(s) that can be used to retrieve copies of the document(s).  An indication
of the relevant sections may also be included but is not required.

[appendix]
== Appendix

=== JSON value equality

Two JSON values are equal if and only if both are:

- `null`, or
- boolean and have the same boolean value, or
- strings and have the same octet sequence, or
- numbers and have the same mathematical value, or
- arrays and have the same number of elements, and elements at the same index are equal according to this definition, or
- objects and have the same property names, and values for the same property name are equal according to this definition.

=== Acknowledgements

The authors acknowledge that the design of the Ion data format was initially influenced by design concepts in
https://tools.ietf.org/html/rfc4287[RFC 4287, The Atom Syndication Format], specifically the parallels between
Atom's 'Entry' and 'Container' concepts and Ion's 'Ion Object' and 'Ion Collection' concepts, respectively.  The
name 'Ion' is a playful nod to the Atom name, honoring this heritage.

.Authors' Addresses

....
Les Hazlewood
Email: les@hazlewood.com
URI: http://leshazlewood.com
Company: Okta
Company URI: https://okta.com
....
